# Generated by Django 4.0.3 on 2022-04-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
    ]
