# Generated by Django 4.0.3 on 2022-04-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
